name: Build .NET

on: [push, pull_request, workflow_dispatch]

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: ${{ secrets.DOTNET_VERSION }}
      DOTNET_SOLUTION: ${{ secrets.DOTNET_SOLUTION }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    steps:
      - name: Call reusable workflow
        uses: PrimeEagle/Reusable-Workflows/.github/workflows/build-dotnet.yml@main
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          solutionPath: ${{ env.DOTNET_SOLUTION }}
          nugetToken: ${{ env.NUGET_TOKEN }}
