
name: Build .NET

on: [push, pull_request, workflow_dispatch]

jobs:
  call-reusable-workflow:
    uses: /PrimeEagle/VNet.Testing/blob/main/.github/workflows/build-dotnet.yml@main
    with:
      dotnetVersion: ${{ secrets.DOTNET_VERSION }}
      solutionPath: ${{ secrets.DOTNET_SOLUTION }}
      nugetToken: ${{ secrets.NUGET_TOKEN }}
